version: '3.4'

# this docker configuation intends to build frontend
# it is supposed that your declared some ENV variables:
#   - ${FRONTEND} points to ${APP} frontend

services:
  frontend-build:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile
      target: ${EXEC_ENV}
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
        sass_registry: ${SASS_REGISTRY}
        MIRROR_DEBIAN: ${MIRROR_DEBIAN}
        app_path: /${APP}
        app_name: ${APP}
        app_ver: ${APP_VERSION}
    image: ${APP}-frontend-${EXEC_ENV}:${APP_VERSION}
    environment:
      - APP
      - APP_VERSION
    container_name: ${APP}-frontend-${EXEC_ENV}
